mobility:
  target: dev
  outputs:
    dev:
      type: trino
      host: trino
      port: 8080
      user: dbt
      catalog: hive
      schema: mobility_gold
      http_scheme: http
      session_properties:
        hive.non-managed-table-writes-enabled: true
        hive.s3.path-style-access: true
